export const PUBLISH_NEW_AERTICLE = 'PUBLISH_NEW_AERTICLE';

export const PUBLISH_EDIT_ARTICLE = 'PUBLISH_EDIT_ARTICLE';

export const PUBLISH_TITLE_CHANGE = 'PUBLISH_TITLE_CHANGE';

export const PUBLISH_SAVE_ARTICLE_CHANGE = 'PUBLISH_SAVE_ARTICLE_CHANGE';

export const PUBLISH_UPDATE_COVER = 'PUBLISH_UPDATE_COVER';

export const PUBLISH_UPDATE_COLUMN = 'PUBLISH_UPDATE_COLUMN';
